sudo: required

language: php

services:
  - docker

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.0
    - php: 5.6

before_script:
  - composer install
  - ./vendor/bin/phpspec

script:
  - php ./vendor/bin/phpspec run
