sudo: required

language: php

services:
  - docker

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.2

before_script:
  - docker pull circlical/phpspec-php7

script:
  - docker run --rm circlical/phpspec-php7 run